-- InsightAgent: PostgreSQL 14+；在空数据库中执行一次。
-- 不包含 DROP；重复执行将报错。后续结构变更通过迁移维护。
BEGIN;

-- 销售区域；region_code 为稳定业务编号。
CREATE TABLE dim_region (
    region_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code varchar(20) NOT NULL UNIQUE,
    region_name varchar(100) NOT NULL,
    country_name varchar(100) NOT NULL DEFAULT '中国',
    province_name varchar(100),
    city_name varchar(100),
    is_active boolean NOT NULL DEFAULT true
);

-- 客户归属区域是当前属性；订单区域保存成交时的归属。
CREATE TABLE dim_customer (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code varchar(20) NOT NULL UNIQUE,
    customer_name varchar(200) NOT NULL,
    industry varchar(100) NOT NULL,
    customer_level varchar(20) NOT NULL,
    region_id bigint NOT NULL REFERENCES dim_region(region_id),
    acquisition_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE dim_product (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code varchar(20) NOT NULL UNIQUE,
    product_name varchar(200) NOT NULL,
    product_line varchar(100) NOT NULL,
    product_category varchar(100) NOT NULL,
    unit varchar(20) NOT NULL DEFAULT '颗',
    standard_price numeric(18,4) NOT NULL CHECK (standard_price >= 0),
    standard_cost numeric(18,4) NOT NULL CHECK (standard_cost >= 0),
    is_active boolean NOT NULL DEFAULT true
);

-- 自然日作为主键；日历字段自动生成，ISO 周需要与 ISO 年一起使用。
CREATE TABLE dim_date (
    date_id date PRIMARY KEY,
    year smallint GENERATED ALWAYS AS (EXTRACT(YEAR FROM date_id)::smallint) STORED,
    quarter smallint GENERATED ALWAYS AS (EXTRACT(QUARTER FROM date_id)::smallint) STORED,
    month smallint GENERATED ALWAYS AS (EXTRACT(MONTH FROM date_id)::smallint) STORED,
    day smallint GENERATED ALWAYS AS (EXTRACT(DAY FROM date_id)::smallint) STORED,
    iso_year smallint GENERATED ALWAYS AS (EXTRACT(ISOYEAR FROM date_id)::smallint) STORED,
    iso_week smallint GENERATED ALWAYS AS (EXTRACT(WEEK FROM date_id)::smallint) STORED,
    day_of_week smallint GENERATED ALWAYS AS (EXTRACT(ISODOW FROM date_id)::smallint) STORED,
    is_weekend boolean GENERATED ALWAYS AS (EXTRACT(ISODOW FROM date_id) IN (6,7)) STORED,
    is_holiday boolean NOT NULL DEFAULT false
);

-- 一行一个订单；金额币种由数据源口径确定；Online Retail II 为 GBP，源数据不单列税费。
-- 订单总金额通过明细汇总，避免订单头和明细出现两套金额。
CREATE TABLE fact_sales_order (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number varchar(40) NOT NULL UNIQUE,
    customer_id bigint NOT NULL REFERENCES dim_customer(customer_id),
    region_id bigint NOT NULL REFERENCES dim_region(region_id),
    order_date date NOT NULL REFERENCES dim_date(date_id),
    -- Online Retail II has no separate confirmation timestamp; the loader maps
    -- InvoiceDate to confirmed_date and records that assumption in its report.
    confirmed_date date REFERENCES dim_date(date_id),
    order_status varchar(20) NOT NULL DEFAULT 'completed'
        CHECK (order_status IN ('pending','completed','cancelled')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_context UNIQUE (order_id, customer_id, region_id, order_date)
);

CREATE INDEX idx_order_confirmed_date ON fact_sales_order (confirmed_date);

-- 一行一个订单行；维度冗余方便分析，复合外键保证与订单头一致。
-- unit_price 为折扣后的成交单价；standard_cost 为成交时单位成本快照。
CREATE TABLE fact_sales_detail (
    order_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    line_number integer NOT NULL CHECK (line_number > 0),
    customer_id bigint NOT NULL,
    product_id bigint NOT NULL REFERENCES dim_product(product_id),
    region_id bigint NOT NULL,
    order_date date NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(18,4) NOT NULL CHECK (unit_price >= 0),
    standard_cost numeric(18,4) NOT NULL CHECK (standard_cost >= 0),
    sales_amount numeric(24,2) GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,
    cost_amount numeric(24,2) GENERATED ALWAYS AS (round(quantity * standard_cost, 2)) STORED,
    gross_profit numeric(24,2) GENERATED ALWAYS AS
        (round(quantity * unit_price, 2) - round(quantity * standard_cost, 2)) STORED,
    gross_margin numeric(18,6) GENERATED ALWAYS AS
        ((round(quantity * unit_price, 2) - round(quantity * standard_cost, 2))
            / NULLIF(round(quantity * unit_price, 2), 0)) STORED,
    CONSTRAINT uq_order_line UNIQUE (order_id, line_number),
    CONSTRAINT fk_detail_order_context FOREIGN KEY (order_id, customer_id, region_id, order_date)
        REFERENCES fact_sales_order (order_id, customer_id, region_id, order_date)
);

CREATE INDEX idx_customer_region ON dim_customer (region_id);
CREATE INDEX idx_order_customer_date ON fact_sales_order (customer_id, order_date);
CREATE INDEX idx_order_region_date ON fact_sales_order (region_id, order_date);
CREATE INDEX idx_order_date ON fact_sales_order (order_date);
CREATE INDEX idx_detail_date ON fact_sales_detail (order_date);
CREATE INDEX idx_detail_customer_date ON fact_sales_detail (customer_id, order_date);
CREATE INDEX idx_detail_product_date ON fact_sales_detail (product_id, order_date);
CREATE INDEX idx_detail_region_date ON fact_sales_detail (region_id, order_date);

COMMENT ON TABLE fact_sales_order IS '订单粒度；收入分析仅纳入 completed 订单';
COMMENT ON TABLE fact_sales_detail IS '订单行粒度；币种取决于导入源，Online Retail II 为 GBP 且成本不可用于毛利分析';
COMMENT ON COLUMN fact_sales_detail.gross_margin IS '比例而非百分数；0.25 表示 25%；零收入时为 NULL';
COMMENT ON COLUMN dim_date.is_holiday IS '法定节假日标记，默认 false，需另行导入日历；不代表调休后的工作日';
COMMIT;
